sciencehistory/chf-sufia

config/initializers/sufia_amendments.rb

Changed 'Penn Libraries' to 'The University of Pennsylvania Libraries'. Also took the opportunity to reorder a genre term.

Change file creator authority, fixes #117

---

app/controllers/catalog_controller.rb
app/views/records/edit_fields/_maker.html.erb

Closes #363
@hackmastera, I think these are the only places to change the UI label "Maker"
to "Creator", my understanding of #363 is we just wanted to change ui labels, not
any underlying field names. 
Is this what you expect for #363?

Change UI label "Maker" to "Creator"

---

lib/capistrano/tasks/invoke.rake

TASK=chf:data_fix:library_division REASON="testing things" UNTIL="12pm Eastern Time" bundle exec cap staging invoke:rake:with_maintenance
Will turn maint mode on for you, run task, turn it back off -- even if
task fails. If you want to leave it on if task fails, SAFE_MAINT=false. 
Or to just run a rake task on a remote server without maint mode:
cap staging invoke:rake TASK=chf:data_fix:whatever

cap tasks for running tasks, including with maintenance mode

---

lib/chf/indexer.rb
lib/chf/indexer/descendant_fetcher.rb
lib/tasks/chf_tasks.rake

* Uses batch and progress bar.
* Indexes permissions objects first, should eliminate double-index need
Based on code already in active-fedora master.
Closes #348
@hackmaster.a I'm not sure how to test to confirm it eliminates need
for double-index. Do you want to do that, or tell me how (what the
problem case looked like before)?

Better mass index

---

app/models/generic_work.rb
spec/models/generic_work_spec.rb

In the case of representative, known to mess up display logic in bad ways, see #394.
In case of thumbnail, just a precaution, enforce what I think are intended semantics.
After spending a couple hours on it, I was not able to find any reasonable
solution to fixing the front-end logic to not infinite loop on this kind
of bad data. The validations should prevent it, not reasonable at this
time to do the other checkbox there. 
Closes #394

validations prevent non-member filesets being saved as thumbnail or representative

---

config/locales/en.yml

Formerly "A PDF is preferred"
Closes #286
I was not able to actually find where the upload a new version is in
the UX, although I know I found it last week! So have not confirmed, but
pretty sure this will remove the prompt.

Remove file hint

---

app/assets/stylesheets/local/upload_works.scss
app/views/curation_concerns/base/new.html.erb
config/locales/sufia.en.yml

1) Different title for single vs batch work upload form. Not sure if there's a better way to organize the i18n keys, this seemed clever to me, or might be too confusing.
2) put batch upload files instructions in alert style to further differentiate batch from single work upload

Solve "Single and Batch Work upload forms too similar in Sufia 7" closes #261

---

config/initializers/curation_concerns.rb

This location used as a holding area for files pulled from fedora for
derivatives generation. Generally not needed during ingest, since the
files are taken from their upload location (managed by CarrierWave).
Sufia made an effort at one point to make sure all CC config values were
managed by Sufia's config, as well, but this one must have slipped
through the cracks. Hence it's in a new CC initializer.

Add configuration for working_path

---

config/initializers/mini_magic.rb

Misspelled the file name when creating this, then it was duplicated when
fixed upstream.

Remove duplicate config file

---

app/models/search_builder.rb
app/models/search_builder/restrict_admin_search_fields.rb
config/initializers/sufia_catalog_search_builder_overrides.rb

Adding it to both places we add SearchBuilder configuration, cause
who knows what sufia/hyrax uses where, and it may change.
Closes #425

Restrict certain search fields to be admin-only

---

config/locales/en.yml
config/locales/generic_work.en.yml

fixes #458
The new file is broken out in support of per-work-type translations (e.g. if we want custom work types with custom metadata profiles for archives vs. oral histories). It was generated in the sufia 7.3 upgrade and I failed to fully attend to it.
Not sure what to make of the old one now; it just has one translation in it but I guess that's fine?

Move generic_work translations to new generic_work locale file, fix #458

---

app/models/search_builder.rb
app/models/search_builder/synthetic_category_limit.rb
app/views/sufia/homepage/_home_content.html.erb
config/initializers/sufia_catalog_search_builder_overrides.rb
lib/chf/synthetic_category.rb
spec/lib/chf/synthetic_category_spec.rb

This is not the final UI. We don't have "splash pages" yet. I don't intend to expose
the synthetic categories on the normal search results page, like it is now. But this gives us
a smaller piece to review, including in production, to make sure the general idea is sound.
refs #434, #435, #436, #437, #438, #439

Start of SyntheticCategories

---

app/controllers/synthetic_category_controller.rb
app/models/search_builder/synthetic_category_limit.rb
app/views/sufia/homepage/_home_content.html.erb
app/views/synthetic_category/_search_form.html.erb
app/views/synthetic_category/_sort_and_per_page.html.erb
app/views/synthetic_category/show.html.erb
config/initializers/sufia_catalog_search_builder_overrides.rb
config/routes.rb
lib/chf/synthetic_category.rb

With more control of titles of synth categories. 
The `synthetic_category_param` is unset, no longer allow query params to
set category limits on ordinary results page, instead you use the category
landing pages, woot.

Synthetic Cateogry landing pages

---

app/controllers/curation_concerns/generic_works_controller.rb
app/views/curation_concerns/base/_relationships_parent_row_empty.html.erb

I am not a huge fan of how I did either of these things either -- I just like
this intervention better than anything else I could come up with, which was even awfuller,
and would involve overriding larger parts of sufia/CC and risking forwards compat problems,
or making the code even more confusing and harder to find what was going on. 
I am thinking when we overhaul the 'show' page generally, I'd like to just override
the actual `show` template, and stop using some parts of the sufia/cc/hyrax abstraction
architecture which are over-engineered and hard to work with without actually providing
customization hooks we need to do what we needed here.
Closes #492 #493

Change 'In generic work' label, and don't show on empty.

---

app/views/synthetic_category/_sort_and_per_page.html.erb

Unlike real collection display, it will show you the count of your result set when
you do a search-inside-the-thing too.
Put it in the space occupied by 'view type' selector in real collections, which we don't use,
since it was available space, and anna said she thought the blank space made things look odd,
and right under the search box seems like a good place when it updates for your current result set.
That means it goes in the "sort and per page" partial, even though it's not really about
sort and per page (neither are view types really!), in order to take advantage of existing
collection CSS consistently.

Add item count to synthetic category collection-like display.

---

app/renderers/curation_concerns/renderers/faceted_attribute_renderer.rb

fixes #544 
With override of curationconcerns class. :(

Fix double-escaping of facet search links

---

app/services/chf/fixity_check_failure_service.rb
config/application.rb
config/initializers/curation_concerns.rb
config/schedule.rb
db/migrate/20170516222881_change_checksum_audit_log.hyrax.rb
db/schema.rb
lib/tasks/chf_tasks.rake
patches/fixity_checks/README.md
patches/fixity_checks/active_fedora/fixity_service.rb
patches/fixity_checks/checksum_audit_log.rb
patches/fixity_checks/curation_concerns/file_set_audit_service.rb
patches/fixity_checks/fixity_check_job.rb
patches/fixity_checks/hyrax/file_set_fixity_check_service.rb
patches/fixity_checks/hyrax/fixity_status_presenter.rb
spec/factories/file_set.rb
spec/services/hyrax/file_set_fixity_check_service_spec.rb

Backported code that I previously contributed to Hyrax. 
May handle #276?
The backport was a bit messy. I tried a new way to organize this code -- a folder at `./app/patches`, that can have subdirs, which have a README describing what they're doing, and include files needed for one conceptual patch or backport.  Added `Dir.glob(Rails.root.join("patches/*"))` to Rails `autoload_paths` to accomplish this. 
This code organization definitely doesn't completely eliminate the pain of dealing with this in the future as we upgrade our dependencies, but it's the best I could come up with. 
What this actually does:
Every day at 2:30am, a fixity check rake task is run. 
* While it runs every day, it currently is set to accept up to 7-day-old existing fixity checks, so won't always re-check …

Fixity in our app

---

config/initializers/sufia.rb

So it's not shared between different dev apps. And so MacOS doesn't delete
all your derivatives from '/tmp' on reboot.

dev sufia data path is in app local tmp

---

config/routes.rb

This is one way to get it to work anyway.
/users/sign_in still works too. Not sure which will be used for internal route-generating.
We can fine-tune this later, but this at least gets /login working so we can
announce the new hostname URL with the easier path at the same time.

/login works as sign_in path

---

app/services/chf/fixity_check_failure_service.rb
spec/services/hyrax/file_set_fixity_check_service_spec.rb

* add Socket.gethostname to fixity check failure subjects
* Don't include internal only IPs. No hostnames at all for now, oh well.
* Do include the fedora bug workaround escaping the colons in fcr:versions

Better fixity failure notification messages

---

app/assets/stylesheets/local/collections.scss

until we get to redesigning this page entirely, keep it working.
before change:

keep collection show image from overflowing it's place

---

Gemfile
Gemfile.lock
app/assets/javascripts/chf_ga_events.js
app/assets/javascripts/chf_image_viewer.js
app/assets/stylesheets/local/chf_image_viewer.scss
app/assets/stylesheets/local/show.scss
app/presenters/curation_concerns/generic_work_show_presenter.rb
app/views/curation_concerns/base/_chf_image_viewer.html.erb
app/views/curation_concerns/base/_chf_image_viewer_navbar.html.erb
app/views/curation_concerns/base/_show_page_image.html.erb
app/views/curation_concerns/base/show.html.erb
config/routes.rb

This is pulled on top of work_show_page branch. 
It's not _quite_ done, but close. 
UI to note:
* Still no high-res images, so you can't actually zoom in very far. 
* tab-to-link nav works on show page and viewer. (mostly, I think). This was surprisingly challenging, but worth it!
* Try out the "full screen" button especially on a large desktop display. How's that for interacting with a text?!?
* Keyboard shortcuts, click the keyboard button to see em
* Yes, I'm not totally happy with the bottom nav bar either, but haven't come up with something better, and I feel like running out of budgetted time on this, have to move on to something else, probably good enough for now. 
* There is a bug in header/footer layout on show page I still need to figure out. 
I am most interested in if you can …

Image viewer

---

app/assets/stylesheets/local/show.scss
app/helpers/curation_concerns_helper.rb
app/helpers/riiif_helper.rb
app/views/curation_concerns/base/_show_page_image.html.erb

Closes #636. 
Just did show page, not viewer. On viewer, using the derivative 'thumb' (which I think we need anyway), is about 2x "retina" size already, and relatively small files already, good enough for now I think.

riiif-provided srcset images on show page

---

app/helpers/riiif_helper.rb
app/models/chf/env.rb
config/application.rb
config/environments/production.rb
config/initializers/riiif.rb
config/routes.rb
lib/tasks/chf_tasks.rake
lib/tasks/dev.rake
spec/models/chf/env_spec.rb

This pulls from the config/local_env.yml if it's present. 
BUT it lets you override that with actual ENV -- awfully useful for testing in dev to make
sure it works how you want in different setings. Also useful if we want to deploy
the app to another environment like heroku that actually uses ENV. 
And it also lets you set a default value, including as a lambda using other env
or config, for us to set our default dev values, or calculate values that aren't
yet in our local_env.yml as independent values. 
The actual implementation of CHF::Env is a bit hacky, although not too complicated,
but I think the API/semantics are pretty good and should be pretty stable. 
In addition, this PR then uses the new CHF::Env for:
* public_riiif_url
* setting riiif file cache paths, with the defaults that …

A CHF::Env class that we will access infrastructure/environmental config from.

---

app/models/solr_document.rb
app/presenters/curation_concerns/generic_work_show_presenter.rb
app/views/curation_concerns/base/_chf_image_viewer.html.erb
app/views/curation_concerns/base/_show_page_image.html.erb
spec/helpers/riiif_helper_spec.rb

I tried this 2 ways; this way seemed a little messy but it works.
The other (see https://github.com/chemheritage/chf-sufia/commit/b8f199e7551a6c4b5ef15bfd8b724cd0e55497e1 on branch empty-child-fix-2) was an attempt to handle it as much as possible in the helper, but it resulted in the viewer failing to show the default thumb, plus there was still a new conditional needed in the download link logic.

Empty child fix

---

app/services/characterization_service_override.rb

grr. fixes bug introduced in #670.

Cast back to string before sending so as not to affect other field types

---

app/assets/javascripts/application.js
app/assets/stylesheets/local/chf_image_viewer.scss
app/assets/stylesheets/local/show.scss
app/presenters/chf/file_set_presenter.rb
app/presenters/curation_concerns/generic_work_show_presenter.rb
app/views/curation_concerns/base/_chf_image_viewer.html.erb
app/views/curation_concerns/base/_show_page_image.html.erb

Takes up proper space on page even before image has loaded, since we tell it expected
aspect ratio, gotten from recorded characterization.
works whether the images is being lazy loaded or normal loaded, nice!
lazysizes-aspectratio is a nice script.
Closes #669

lazysizes-aspectratio on all show page images and viewer thumbs

---

config/deploy.rb

This keeps the riif box from trying to run the resque-pool init script.

Resque should only restart on a bg jobs machine

---

app/helpers/riiif_helper.rb
app/models/chf/env.rb
app/views/curation_concerns/base/_show_page_image.html.erb
spec/models/chf/env_spec.rb

To accomplish, also refactored _show_page_image image tag generation to a
unified member_image_tag helper. Which will make it easier to do the GA
stuff in #668
Currently defaults to using riiif. If we don't want to use riiif, we could
change the default, or just add a key in local_env.yml,
use_image_server_on_show_page: false
You can experiment in dev to see both modes by starting up as:
USE_IMAGE_SERVER_ON_SHOW_PAGE=false rails server
USE_IMAGE_SERVER_ON_SHOW_PAGE=true rails server
Closes #686

App will use images on show page from riiif or hydra-derivative 'jpeg' depending on config

---

app/assets/javascripts/chf_image_viewer.js

It was going away too early, now we wait until we have at least one
actual tile draw before removing it.

more reliable OSD spinner

---

app/assets/javascripts/chf_ga_events.js
app/assets/javascripts/chf_image_viewer.js
app/helpers/riiif_helper.rb
app/views/curation_concerns/base/_chf_download_menu.html.erb
app/views/curation_concerns/base/_show_page_image.html.erb

Variable names in the generalized javascript have been changed to match google analytics. The generalized js now requires a class, and looks up the element's hierarchy to find it if it's not on the target element. This allows the container div to hold the ga data, but still use the generalized javascript.

Sort out google analytics semantics, pass desired data; fixes #668

---

app/models/chf/env.rb
app/views/curation_concerns/base/_chf_download_menu.html.erb
app/views/curation_concerns/base/_chf_image_viewer.html.erb

All riiif use feature flags DEFAULT false now.
To verify everything is working with no riiif server in dev, you could:
SERVE_RIIIF_PATHS=false rails server
If you wanted to turn on riiif features in dev, you could:
USE_IMAGE_SERVER_ON_SHOW_PAGE=true USE_IMAGE_SERVER_DOWNLOADS=true USE_IMAGE_SERVER_ON_VIEWER=true rails server
All feature flags also can be controlled from local_env.yml but they are all currently
defaulting false.

CHF::Env feature flags to turn off riiif use on viewer and download link

---

app/overrides/solrizer_override.rb

Solrizer.solr_name is called a lot on our show page.
Profiling revealed it was somehow a bottleneck. This helped.

override Solrizer to cache, speed up

---

app/models/chf/rights_terms.rb
app/presenters/curation_concerns/generic_work_show_presenter.rb
spec/models/chf/rights_terms_spec.rb

We were using , from QA gem.
This ended up re-loading YAML from disk on every call. Either the QA code needs caching
it doesn't have, or we're using QA wrong, or both.  Rather than figure it out,
we write our own simple wrapper to get the info from the same .yml file,
and make sure it's cached globally. Nothing fancy about this no reason
not to write ourselves.

look up rights metadata for rights statements faster

---

app/views/curation_concerns/base/_show_page_image_file_set_actions.html.erb

It turns out calling Sufia helper application_name is quite expensive, too
expensive to do twice per member on a page that could have hundreds of members.
Sufia::SufiaHelperBehavior#application_name
We could have tried to figure out why it was expensive and optimized it, but
we don't need it enough to be worth the time at present.
PR'd to riiif branch, because this .erb code changed it's location
between master and riiif, didn't want to deal with the merge.

avoid expensive application_name call

---

app/assets/stylesheets/local/show.scss
app/views/curation_concerns/base/_chf_download_menu.html.erb

This did have significant perf impact.
Turning it into a helper instead of a partial had the same perf impact, if we wanted to keep DRY.
But I think this was a false DRY in the first place, it really IS a
different thing, the code is actually _cleaner_ with it being separate,
with it's completely own CSS class, trying to override the CSS
for the 'large' rights statement didn't make a lot of sense or make
the CSS easier to deal with. (The CSS here is still kind of a mess,
but only trying to fix what's relevant for the perf improvement here.
writing maintainable CSS is not something I'm great at yet.)
Note that all the actual heavy-lifting is done by calls to
the presenters _anyway_ (which then call out to CHF::RightsStatement
in turn).  There was just no good reason for the additional …

inline rights_statement in _chf_download_menu

---

app/indexers/generic_work_indexer.rb

For use on show page. This branch doesn't use them on show page yet, but we need to index
them here on master, before we merge riiif in

Index representative original_file_id, width, and height

---

app/indexers/chf/generic_work_indexer.rb
app/presenters/curation_concerns/generic_work_show_presenter.rb

It results in three trips to Solr and is too expensive.
To avoid it, we index the data we need directly on the work itself.
This does seem to significantly improve performance, and is probably the cause of
our last remaining perf problem crosses fingers.
I separately PR'd the indexing changes to master. I did them here too, which
might cause a conflict on merge, but since the GenericWorkIndexer changes
paths between the branches, I was worried it might end up lost entirely
and not properly merged without a conflcit, I'd rather a conflict so
we make sure it winds up here.

Avoid calling representative_presenter for each child work on a parent show page

---

app/indexers/generic_work_indexer.rb
app/models/generic_work.rb
spec/factories/generic_works.rb
spec/indexers/generic_work_indexer_spec.rb

With tests for edge cases I could think of.
Ended up simpler code doing some TDD-ish dev, hooray.
Tricky taking care of reindexing a work when it has a child work as a representative, and that child work's representative has changed. Have to put some expensive solr lookups in indexing. 
Tests are pretty slow, maybe another 30s to these new tests. Best I could come up with so far. Wary of mocking too much stuff that I'm not super confident won't change in a future version, causing tests to false pass.

improve work indexing of representative data

---

app/helpers/image_service_helper.rb
app/helpers/member_helper.rb
app/models/chf/env.rb
app/presenters/chf/file_set_presenter.rb
app/presenters/curation_concerns/generic_work_show_presenter.rb
app/views/curation_concerns/base/_chf_image_viewer.html.erb
lib/chf/utils/iiif_original_preloader.rb
lib/chf/utils/riiif_original_preloader.rb
lib/tasks/chf_tasks.rake
lib/tasks/dev.rake
spec/helpers/image_service_helper_spec.rb
spec/presenters/chf/file_set_presenter_spec.rb
spec/presenters/curation_concerns/generic_work_show_presenter_spec.rb

Show page verified working with riiif, cantaloupe, and neither (derivative thumbnails).
iiif preload verified working with riiif and cantaloupe.
Configuration now must be provided for a full url, including base path, e.g. (cantaloupe local_env.yml example) `iiif_public_url: //images.digital.chemheritage.org:8080/iiif/2` or (riiif ENV example) `IIIF_INTERNAL_URL=http://localhost:3000/image-service`
@jrochkind I believe this addresses all your notes from #739 except https://github.com/chemheritage/chf-sufia/pull/739/files/baf22ad92add4758e175220dce9adf766b7fe923#r130358339 since I couldn't think of a case where we would be using those. But if you think it's important I can do it or you can change it!

Generalize from `riiif` to `iiif`, allowing for use of cantaloupe or any iiif image server

---

app/assets/javascripts/chf_image_viewer.js

For certain kinds of errors, a spinner was left forever, now we notice
and remove spinner, and add error message if needed. should make
debugging a little bit less confusing in some cases.

image viewer, more robust errors

---

app/controllers/downloads_controller_override.rb

https://github.com/samvera/hydra-head/pull/421

use response.body=stream rails api to get quicker HTTP headers

---

app/assets/javascripts/chf_image_viewer.js

OSD continues to call its update method when the modal is hidden. Closing it will keep it from running when out of site.
Still unclear why this only causes problems with cantaloupe, and for only some images. Here is where I stopped with my debug efforts:
Upload a file which was causing us problems, e.g. http://54.174.106.16/concern/generic_works/kp78gg445
with a breakpoint at this line you can open the viewer, then hit 'play', then zoom in then close the viewer, and drop into the browser's debugger at the right time
https://github.com/cbeer/openseadragon-rails/blob/master/vendor/assets/javascripts/openseadragon/openseadragon.js#L10126
Then I set other breakpoints because it takes a lot of stepping to get to a problem area.
For example, you can set a breakpoint at …

Fix viewer freeze on close with cantaloupe

---

app/indexers/chf/file_set_indexer.rb
app/indexers/chf/generic_work_indexer.rb
app/models/generic_work.rb
app/presenters/chf/file_set_presenter.rb
app/presenters/curation_concerns/generic_work_show_presenter.rb
spec/indexers/chf/file_set_indexer_spec.rb
spec/indexers/chf/generic_work_indexer_spec.rb

Using the checksum in the URL for assets is nice, becuase it menas you can make
them infinitely cacheable (For instance for browsers), even if the image behind
a file_id changes (versions?).  I am doing this for DZI experiment, but it's
potentially applicable to all our image sources. 
But that means it's gotta be indexed, so you have it to generate the URLs
at display time. 
Yes, this apparently requires touching five different files!

Index representative_checksum too, for fingerprinted URLs

---

app/forms/concerns/work_form_behavior.rb
spec/controllers/curation_concerns/generic_works_controller_spec.rb
spec/features/generic_work_form_spec.rb

Looks like whatever was preventing me from doing feature specs involving form submission is resolved. I must have made a config change somewhere along the way that fixed this!
This PR includes another feature spec fix which I did first just to see whether they were working.

Allow physical container to be emptied; add feature spec to prevent regression

---

app/controllers/catalog_controller.rb

@jrochkind any reason why our default search fields shouldn't be the same as our 'all fields' keyword search?

Set default search fields to the same as 'all fields', fixes #673

---

config/schedule.rb

The rails postgres wasn't configured to allow connections outside of localhost. We probably should change that; definitely will need to if we want to move fixity cron onto jobs box. Changing that configuration will require scheduled downtime for the staff side (will there be an impact for non-logged-in users?)
In the meantime move this cron back to the app box.

Move fixity cron back to app box

---

app/views/sufia/uploads/_js_templates.html.erb

I noticed this file did not get upstream changes in the 7.3 upgrade
while investigating for #638. I don't think this was in any way related
to that issue, nor do I think we had other bugs, but these changes have
been incorporated upstream (with minor variation) so it's better to
realign.

Align _js_templates.html.erb with changes upstream from sufia 7.3

---

app/uploaders/sufia/uploaded_file_uploader_override.rb

Code works but fix is unconfirmed since the bug can't be replicated. Users have been
instructed to let us know if they see it again.

Rename method that mistakenly overwrites super; may fix #638

---

app/helpers/member_helper.rb

Since for now we only have one download option, the sub-heading label was
confusing people. Closes #737

Change download menu text

---

app/forms/batch_edit_form.rb
app/forms/concerns/work_form_behavior.rb
config/application.rb
lib/chf/data_fixes/genre_charts.rb
lib/tasks/data_fixes.rake

Pending testing on staging.
This PR:
- Adds the new option to the form.
- Adds the migration task.
- Adds a data filter to form processing that catches any attempts to save the old term and converts it into the new term. This will keep new edits from creeping in after the task has run but before the old option has been removed from the form. This code is intended to be temporary, removed in the follow-on PR. Thus it is isolated in its own commit.
The removal of the old option is in a follow-on PR
Refs #562

Charts genre step 1

---

app/assets/javascripts/chf_image_viewer.js

For some reason straight dom JS on FF was going vertical, jquery equivs work right on FF too

use jquery instead of straight dom js for identifying viewer next/prev

---

app/assets/javascripts/chf_image_viewer.js

Even though we're using jquery to lookup next/prev, need to get an actual
DOM object cause that's what selectThumb expects. Thought I was doing that,
but wasn't.

Need an actual DOM object

---

app/assets/stylesheets/local/chf_image_viewer.scss
app/assets/stylesheets/local/show.scss
app/helpers/member_helper.rb
app/views/curation_concerns/base/_chf_image_viewer.html.erb

See individual commits. Includes removing use of js lazy aspectratios
in viewer thumbs, for hard-coded ones instead. 
I believe lazyloading with aspectratios should be working well here,
and no longer will a direct to /viewer link on a many-membered work
freeze up the browser for a while. 
One thing we might want to do that I have NOT done yet is replace
the animated spinner with a static wait/progress icon of some kind. 
I think so many instances of that animated spinner on a page are putting
stress on CPU. 
Ref #792 #793

Improvements to lazyloading images and aspectratios

---

app/indexers/chf/generic_work_indexer.rb

Turns out we actually need this to properly display thumbs for a work even with
multiple levels of nesting. didn't run into the bug in production cause we don't
have those. But in results refresh, we run into it attmepting to make thumbs.
This commit just establishes the indexing, nothing uses it. Index only commit
to master, so we can reindex before we have anything that uses it.
Requires reindex after deploy.

index work representative_file_set_id

---

lib/chf/indexer.rb
lib/tasks/chf_tasks.rake

Records that existed from before the reindex and weren't touched. Ie, records that were deleted in the
original store, but still had existed in the index somehow.
DELETE_PREVIOUS=true bundle exec rake chf:reindex
@sanfordd note new option to chf:reindex task, can now delete deleted/not-present
records, based on them being records that weren't touched in the reindex.

reindex and then delete older records

---

lib/tasks/chf_tasks.rake

Applies a read permission to all objects in the dzi bucket. Means that the permission for access is now at the bucket level if we need to copy items between buckets, which causes a loss of ACLs, or any other edits that might cause an object to lose the ACL for access.
Bucket policy was taken from the AWS default example for universal read access.

S3 permissions

---

app/presenters/curation_concerns/generic_work_show_presenter.rb
app/presenters/curation_concerns/member_presenter_factory_override.rb
spec/views/curation_concerns/base/show.html.erb_spec.rb

previous version was doing a solr request for every single member, to get it's access control info :(

enforce access-hiding on show page, without trigger solr n+1

---

solr/config/schema.xml

http://awead.github.io/fedora-tests/
Solr will need to be restarted after deploying this for it to take effect,
it looks to me like Solr actually is restarted as part of our ordinary every
cap deploy. `after "deploy:log_revision", "chf:restart_or_reload_solr"`

don't copyfield to suggest on indexing

---

app/models/chf/env.rb
app/views/application/robots.txt.erb
config/routes.rb
public/robots.txt

Closes #865
Note crawl-delay is still a high 5 as it was previously, not sure if we really need that,
might help to lower it to get indexed, but not doing it now. We have no docs of
the crawl-delay decision, if we really needed it at one point or not.

Dynamic robots.txt, disallowing all in non-production

---

app/presenters/curation_concerns/generic_work_show_presenter.rb
app/views/curation_concerns/base/_show_page_image.html.erb
app/views/curation_concerns/base/show.html.erb

Not it's ultimate representative fileset. Our architectural changes mean it can already handle
this just fine. It allows us to provide the 'info' button for child work even in representative
position, while still providing download button for actual fileset (when in representative position).
All this is getting convoluted, it's hard to figure out UI for generic child work situation.
Closes #897

Use child work as representative presenter on show page

---

app/controllers/curation_concerns/file_sets_controller_override.rb
app/views/curation_concerns/file_sets/_show_actions.html.erb
config/application.rb

_social_media partial was being rendered on file set page, and then expecting our custom filesetpresenter. 
we fix in two ways: make sure our custom fileset presenter is used in FileSetsController, but also stop
rendering social media buttons on file set page, they don't work right anyway, we don't need them there.

fix social media bug

---

app/assets/javascripts/edit_metadata.js

don't really understand what's going on with this code, that was previously localized/forked
for reasons I'm not sure of. But this works around the bug. There are apparently two different
autocomplete mechanisms still fighting with each other here.
Closes #719

fix autocomplete but with hacky workaround

---

app/services/chf/create_derivatives_on_s3_service.rb

Should download as UTF-8 where browsers recognize, else an ascii version.
fixes #957

handle non-ASCII filenames for S3 downloads

---

app/views/curation_concerns/base/show.html.erb

The original defaults don't work well, and we haven't yet had time to make better.

comment out citation links for now

---

Gemfile.lock

newer webmock is needed to work under ruby 2.4+, found when accidentally trying to run tests under ruby 2.5. We're still using 2.3 in production but might as well preemptively upgrade.

upgrade webmock dependency

---

app/models/user.rb
config/initializers/devise.rb
lib/chf/env.rb

Implemented super cheesy hacky. 
1. Hook into a devise feature meant for user 'activation' to let all users not login
2. be even meaner to devise by using some hacky ruby/rails craziness to tell it not to present
the usual login screen if we have logins disabled. 
If we set logins to be disabled, and a logged in user accesses the app, they will be immediately logged out. 
If they were trying to do something that required a login, they'll be redirected to the 'login' screen, which
has been replaced with a message actually saying "Sorry, logins disabled."
They'll have to login again when logins are no longer disabled. 
If they never accessed the app when logins were disabled, they'll find themselves still logged in after the window though. But if they acccess during window, they'll get …

Feature to log out admin logins while leaving public app up

---

README.md

Don't use markdown a lot - hope this works.

Edit the README.md to remind new users to add a default Sipity workflow.

---

app/indexers/chf/generic_work_indexer.rb
spec/indexers/chf/generic_work_indexer_spec.rb

* Needed for DPLA oai-dc metadata, dc:format, PA Digital recommends. ref #965
* Am a bit worried about it slowing down indexing, if indexing wasn't already fetching all members. But it appears to be okay for our standard use cases, in limited tests. Not sure if indexing was already pulling in members.
* For reasons of above, this does NOT try to descend into work-member children, just top level fileset children.

index MIME/IANA content-types for works

---

app/models/chf/citable_attributes.rb
config/environments/production.rb
config/environments/profile.rb
config/sitemap.rb
lib/chf/env.rb
lib/tasks/chf_tasks.rake.new
spec/features/site_map_spec.rb
spec/models/chf/citable_attributes_spec.rb
spec/models/chf/ris_serializer_spec.rb

It was starting to proliferate, seemed to make sense to centralize, even though we don't expect a name change again anytime soon!
Also lets us have the proper hostnames for staging, and test/dev while we're at it.

Keep baseurl/hostname digital.sciencehistory.org in Env for re-use

---

app/indexers/chf/file_set_indexer.rb

so we can filter to just public, in memory.
Needed for PDF creation, make a PDF of just public members
This stack is so ridiculous.

get fileset to index visibility

---

app/indexers/chf/generic_work_indexer.rb
spec/features/new_work_feature_spec.rb

This is a potential fix for #1049 .
Here's what I think is going on:
1) The generic work indexer is not deduplicating date objects before indexing them, as it does for some of the other fields it handles. This leads to duplicates in the SOLR field date_of_work_json_ssm .
2) The way the front-end display handled dates until a couple weeks ago masked this problem by deduplicating the date_of_work_json_ssm items at display time. ( I haven't investigated quite how yet.)
3) When [I changed the way front-end dates were displayed a couple weeks ago](https://github.com/sciencehistory/chf-sufia/commit/2556ae9cc3154025772a76c8d94ed4d4037c9d12), I used the data in date_of_work_json_ssm directly, thus exposing the problem described in 1).
I feel the best way to fix this problem is to modify the …

Duplicate date bugfix

---

app/controllers/downloads_controller_override.rb
app/models/chf/oai_dc_serialization.rb
app/services/chf/create_derivatives_on_s3_service.rb
app/services/chf/dzi_s3_url_service.rb
app/services/chf/legacy_asset_url_service.rb

Per PA Digital request. We still want to send the "download-medium" size one, which is a nice size, same one we use for fb share.
Had to muck about with our homegrown API for images which has grown confusing and ill-suited for our actual needs, it turns out. Sufia lacked suitable APIs so we had to do something, sorry about the spaghetti. 
Failing on travis because of downloading-solr problem. Confirmed test suite passes locally.

Get OAI-PMH feed to include thumbs that don't content-disposition force download

---

app/forms/batch_edit_form.rb
spec/features/batch_edit_bug_spec.rb
spec/features/batch_edit_feature_spec.rb
spec/forms/batch_edit_form_spec.rb

Fixes #925 
This is only a first try, and probably contains bugs. Obviously a screwed-up batch edit attempt could ruin a lot of metadata, so it's worth testing this really carefully.
* I pulled method initialize_combined_fields from the superclass and modified it so it works with single-value fields.
* I'm also adding rights_holder and file_creator to this, as they seem to work largely the same way. Obviously we may not want them in the form, but I figured why not.

WIP Batch edit changes

---

Gemfile.lock

https://github.com/plataformatec/devise/issues/4719
After this update, all our tests pass on ruby 2.5.1. 
Ref #806

update devise to a version that works under ruby 2.5.1

---

app/assets/javascripts/accept_cookies_banner.js
app/assets/stylesheets/local/footer.scss

- Changing accept button colors (basic color is brand red and hover color is brand blue)
- Increasing height of accept button
- adding event.prevent default to cookie accept js function
- setting bottom nav color to white (might later set it to off-white.)

Adjustments to the GDPR cookie accept banner

---

.travis.yml
config/database.yml

Be more consistent with prod, and sqlite3 has problems with lots of concurrent access sometimes, which sufia ingest can do.

Use postgres in dev and test, instead of sqlite3

---

.travis.yml
Gemfile
Gemfile.lock
README.md
config/database.yml

The "bundle install" command should no longer need to install sqlite, since we're no longer using it in development, staging, or production.

Remove sqlite dependency

---

app/controllers/admin/fixity_controller.rb
app/views/admin/fixity/index.html.erb

No need to cause unnecessary panic. Fixes #1089.

Don't throw a 500 error when there are no fixity checks in the database.

---

lib/tasks/clean_up_orphaned_fixity_records.rake

Adding Ldp::Gone to list of exceptions to catch in identifying vanished FileSets.
Two different exceptions get thrown depending on whether a placeholder is left when a FileSet is deleted. We want to delete the fixity check records in either case.

Tweak the orphaned fixity check cleanup script

---

app/jobs/batch_create_job.rb

Closes #1114
Our code was wrapping an extra array where it shouldn't have, not sure why, something lost in translation of copying and customizing sufia code.
In testing period, nobody tested batch upload of _local_ files with 'formats' selected, which is the only time it would occur.

Fix bug with batch ingest with formats selected

---

Gemfile
Gemfile.lock
spec/services/chf/opac_record_service_spec.rb

From 11.1.6
To upgrade activefedora we also had to upgrade other dependencies, so as to be compatible.
This is to get a version of active-fedora which fixes this bug:
https://github.com/samvera/hyrax/issues/2108
Which seems to be responsible for this bad behavior in our app:
https://github.com/sciencehistory/chf-sufia/issues/1105
It's a mystery why we didn't run into this active-fedora bug until now, but this does seem to fix it.
However, upgrading active-fedora required upgrading faraday, which made some automated tests fail around our "OPAC Service" scraping functionality. There was a comment note from @hackmastera saying it would, although it's mysterious why.
I believe we do not actually use that functionality anymore, and can probably just remove those tests and/or all the code …

upgrade active_fedora to 11.5.2

---

app/helpers/recent_items_helper.rb

Recent Items has been live for a couple weeks now.
- To make the selection more interesting, we're increasing the size of the bag from which recent items candidates are picked at random. Was 15; is now 50.
- Any other suggestions for adjustments or fixes welcome.

Tweaks to the "Recent Items" feature.

---

spec/features/search_feature_spec.rb

for some reason only fails on travis, where the cookie banner is getting in the way:
Firing a click at co-ordinates [386, 701] failed. Poltergeist detected another element with CSS selector 'html.fixedsticky-withoutfixedfixed body.localized-layout.branded-body-font nav.navbar.navbar-default.navbar-fixed-bottom.accept_cookies_banner_nav div#accept_cookies_banner_container.container-fluid div.row div#accept_cookies_copy.col-sm-10.i-accept-copy' at this position. It may be overlapping the element you are trying to interact with. If you don't care about overlapping elements, try using node.trigger('click').

accept cookie banner in capybara test

---

config/solr_wrapper_test.yml

Our travis builds are failing with network errors again trying to download solr. Will this fix it?

use princeton mirror url for downloading solr in test

---

app/controllers/collections_show_controller.rb

These tweaks avoid two recent errors we've gotten in production by checking search inputs before they are sent to blacklight_range_limit. Fixes https://github.com/sciencehistory/chf-sufia/issues/1144
Note: I'm also going to suggest a fix to the actual blacklight_range_limit project based on https://github.com/sciencehistory/chf-sufia/pull/1126 .

Extra blacklight validation

---

config/solr_wrapper_test.yml

To avoid having to monkey patch solr_wrapper, as detailed in https://github.com/sciencehistory/chf-sufia/pull/1153/ , we're simply avoiding using the Princeton mirror for solr.

Remove solr_wrapper mirror_url setting.

---

Gemfile.lock

avoids warning on CVE-2018-1000201, which doesn't really apply to us anyway cause we're not on windows

update ffi gem

---

app/assets/javascripts/accept_cookies_banner.js
config/application.rb

Also fixing a bug in https://github.com/sciencehistory/chf-sufia/pull/1143 bug. We want to show the GDPR banner by default in dev and production, and hide it from the unit tests. See the note at https://github.com/sciencehistory/chf-sufia/pull/1143/files#r216418234 .
Fixes https://github.com/sciencehistory/chf-sufia/issues/1154 .

Adding an expiration date for the GPDR cookie.

---

app/helpers/application_helper.rb

Misspelled right statement URIs should not trigger a 500 error.

---

Gemfile.lock

CVE-2018-16468
nokogiri update comes along with it since nokogiri is a loofah dependency, that's fine.

update loofah dependency

---

app/helpers/description_formatter_helper.rb
app/sanitizers/description_sanitizer.rb
app/views/collections/_collection_description.erb
app/views/curation_concerns/base/_work_description.html.erb
spec/features/collection_feature_spec.rb

Uses nokogiri to add in the new link attribute.
Note that the target=_blank is not stored, but added at display time; the tests reflect this.
Fixes #1183

Adding a target=_blank to description links

---

app/sanitizers/description_sanitizer.rb
spec/controllers/collections_controller_spec.rb
spec/features/collection_feature_spec.rb

Fixing typo w/ description sanitizer

---

.travis.yml

This PR removes a now-unused setting from Travis config.
- `[ci skip]`, since it's just configuration.

Travis: Remove unused directive sudo: false

---

app/controllers/catalog_controller.rb
app/forms/batch_edit_form.rb
app/forms/batch_upload_form.rb
app/forms/curation_concerns/generic_work_form.rb
app/models/concerns/generic_metadata.rb
app/models/solr_document.rb
app/presenters/curation_concerns/generic_work_show_presenter.rb
app/views/curation_concerns/base/_attribute_rows.html.erb
app/views/curation_concerns/base/show.html.erb
app/views/records/edit_fields/_project.html.erb
config/application.rb
config/locales/generic_work.en.yml
spec/exporters/collection_exporter_spec.rb
spec/exporters/file_set_exporter_spec.rb
spec/exporters/generic_work_exporter_spec.rb
spec/forms/batch_edit_form_spec.rb
spec/forms/batch_upload_form_spec.rb
spec/forms/curation_concerns/generic_work_form_spec.rb
spec/indexers/chf/generic_work_indexer_spec.rb
spec/views/curation_concerns/base/_form_metadata.html.erb_spec.rb

A "Project" metadata field for GenericWorks. Fixes #1240.
Includes tests, including for the export.
Note: I discovered we didn't have tests for the exporters, so this PR includes a minimum of exporter test functionality-- just enough to be able to assert that the new field is in fact included in the export.
I'll flesh it out soon in another PR.

"Project" metadata field

---

app/assets/stylesheets/local/work-show.scss
app/views/curation_concerns/base/show.html.erb

Several small changes to the feature in progress:
- Added horizontal space under the show notes field
- Renamed the show notes link to read "Show notes" instead of Notes...
- Changed the html #id of the provenance notes div

Display adjustments to provenance/provenance notes

---

spec/features/new_work_feature_spec.rb

Using actual data from a museum provenance record.

Add provenance to the new work feature test.

---

lib/tasks/grant_edit.rake

Because of this bug #1192 , plus the limitations of the Sufia UI, there's no practical way to grant mass edit access to a category of records to a new user. This is a band-aid intended to tide us over until we can switch to the new system and we have a sane permissions system again.

Rake task for granting access to all museum images to a new user.

---

app/assets/javascripts/chf_ga_events.js

Without customizing sufia, so it doesn't make it very easy to hook into to issue a google event, so we hackily watch for clicks and look at actual text of link

attempt to track 'Back to search reuslts' clicks

---

config/deploy/production.rb

This'll let us deploy to the correct server since we've switched the old URL to the new application.

new url for sufia application

---

.travis.yml

Try get around weird rubygems bug that's suddenly started affecting us:
https://bundler.io/blog/2019/05/14/solutions-for-cant-find-gem-bundler-with-executable-bundle.html
Looks like this in travis log with test failure:
```
/home/travis/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
```
Not sure why it doesn't reproduce locally, just on travis.

Tell travis to update rubygems before running
