sciencehistory/chf-sufia

config/initializers/sufia_amendments.rb
=> Add 'negatives' to Genre terms

config/initializers/sufia.rb
On my dev machine, fits is just called 'fits'
@hackmastera what do you think of this solution?
=> dynamically look up fits_path

lib/chf/metadata/related_url_report.rb, lib/tasks/chf_tasks.rake
rake chf:related_url_csv[/path/to/output.csv]
fixes #344
=> related url report as csv

app/controllers/catalog_controller.rb, app/indexers/generic_work_indexer.rb, app/models/concerns/generic_metadata.rb
This PR includes 2 other cleanup-type commits for my own convenience but let me know if you prefer them split out.
=> Add desired fields to 'all fields' search, fixes #351

Gemfile, Gemfile.lock, lib/chf/data_fixes/work_dates.rb, lib/tasks/data_fixes.rake
RAILS_ENV=production bundle exec rake chf:data_fix:fix_work_dates
Still in progress on staging, seems to be taking hours, not sure if it
really should be expected to?
=> rake task to fix String dates, fixes #322

app/controllers/catalog_controller.rb, app/indexers/generic_work_indexer.rb
Copies four place-related properties over into a solr field for facet
Closes #346
=> Place facet

Gemfile, Gemfile.lock, lib/chf/data_fixes/add_catlu_access.rb, lib/chf/data_fixes/work_dates.rb, lib/tasks/data_fixes.rake
This is on top of #386, merge that first
rake chf:data_fixes:add_catlu_access
=> Add edit access to 'catlu' for all records, fixes 370

app/controllers/catalog_controller.rb, app/presenters/chf_index_presenter.rb
Closes #331
This is a totally insane way to do this, but I think might be
the bet we've got?
When/if we overhaul our front-end, I would anticipate possibly doing
the front-end templates in a different way, cause this architecture
is wacky. We'll see.
=> Truncate description in search results

app/controllers/catalog_controller.rb
=> Update fields displayed for search results

lib/tasks/chf_tasks.rake
* Only does works to prevent the slower find all fedora ids task
* batches solr adds
* uses a progress bar
=> Super fast reindex_works tasks

lib/tasks/chf_tasks.rake
=> reindex_works, make solr commits more like what I THINK

app/models/file_set.rb
Not closing the issue because we'll also need to regenerate derivatives to fully resolve the bug.
=> Only run layer 0 in derivative jobs, refs #288

config/application.rb, lib/chf/data_fixes/genre_document.rb, lib/tasks/data_fixes.rake
=> Change Genre term "Records (Documents)" to "Documents"

app/views/curation_concerns/base/_attribute_rows.html.erb
=> 'Place of creation' dropdown should be before 'place of interview' in edit view

app/controllers/catalog_controller.rb
=> 'Medium' facet should only show for logged-in users

config/authorities/resource_types.yml
=> 'Moving image' selection proper order

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/stylesheets/application.css, app/controllers/catalog_controller.rb, app/controllers/my_controller.rb, app/indexers/generic_work_indexer.rb, app/indexers/generic_work_indexer/date_values.rb, app/models/search_builder.rb, config/initializers/sufia_catalog_search_builder_overrides.rb, config/routes.rb, spec/factories/generic_works.rb, spec/indexers/generic_work_indexer/date_values_spec.rb, spec/indexers/generic_work_indexer_spec.rb
This needs to be evaluated by stakeholders for UX -- either we need to reserve staging for a few days for that, or we can just deploy to production and get eval there before closing issue #329
Some oddities to keep aware of:
* The potential date input is various, and includes possible ambiguous or erroneous dates, or date information it's hard to represent completely accurately in a timeline/facet limit. 
* If a date is marked 'before', 'after', or 'circa', it's indexed for the limit the same as if it had no qualifier at all. "before 1950" is put on the timeline at 1950. 
* If a date has a 'start' of "decade" or "century", the "finish" is _ignored_.  Something entered as "Start: 1950s, End: 1962", will jut be indexed as "1950s", ie 1950-1959.  
* A finish _before_ a start is ignored, just …
=> WIP date range facet/slider

config/locales/sufia.en.yml
=> Change search label 'All of Sufia' to just 'All', fixes #447

app/controllers/catalog_controller.rb, app/indexers/generic_work_indexer.rb
=> index rights labels for search

app/assets/stylesheets/local/index.scss, config/locales/blacklight.en.yml
=> change date facet submit button styling

app/assets/stylesheets/local/index.scss
=> Remove brokenly styled numbers on search results

app/presenters/curation_concerns/generic_work_show_presenter.rb, app/views/curation_concerns/base/_large_rights_statement.html.erb
just skip display of large rights statement
Closes #474
=> display okay even if no rights statement

app/assets/javascripts/application.js, app/assets/javascripts/sufia/uploader.js
=> localize sufia/uploader.js to override max file size

app/assets/javascripts/sufia/uploader.js
=> What do we want? 5G UPLOADS! When do we want it? NOW! Closes #190 again. 

Gemfile, Gemfile.lock
=> Pull in curation concerns fix to allow sharing on creation, closes #462

lib/chf/utils/admin.rb, lib/tasks/chf_tasks.rake, spec/lib/chf/utils/admin_spec.rb
=> Add rake tasks to set up admin role, admin users

spec/factories/users.rb, spec/models/ability_spec.rb
refactor ability spec and demonstrate that admins already have update access to all files. closes #478
=> Admin access

app/models/ability.rb, app/views/batch_edits/_delete_selected.html.erb, app/views/curation_concerns/base/_show_actions.html.erb, app/views/curation_concerns/base/unauthorized.html.erb, app/views/curation_concerns/file_sets/_show_actions.html.erb, app/views/my/_work_action_menu.html.erb, spec/models/ability_spec.rb, spec/views/batch_edits/_delete_selected.html.erb_spec.rb, spec/views/curation_concerns/base/_show_actions.html.erb_spec.rb, spec/views/curation_concerns/file_sets/_show_actions.html.erb_spec.rb, spec/views/my/_work_action_menu.html.erb_spec.rb
=> Only an admin can delete things

lib/tasks/chf_tasks.rake, lib/tasks/dev.rake
and a typo fix in chf:admin:grant
=> some useful data cleanout tasks for dev

solr/config/solrconfig.xml
Solr will need to be restarted on deploy.
=> Add TermsComponent to solrconfig, fixes #503

lib/chf/synthetic_category.rb
Closes #523 closes #522 closes #521 closes #520 closes #519 closes #518
=> synthentic category descriptions

app/assets/stylesheets/local/site-wide.scss, app/views/_controls.html.erb, app/views/_masthead.html.erb
Still more to do on the navbar, but this is in a mergeable state as we continue making progress.
=> Add new navbar and reorganize navigation elements, refs #552

app/controllers/sufia/homepage_controller_override.rb, app/views/layouts/homepage.html.erb, config/application.rb, spec/controllers/sufia/homepage_controller_spec.rb
=> Home layout

app/controllers/synthetic_category_controller.rb
Fixes #563
I don't fully understand what's going on here, but this should fix it, seems
to in dev.
=> fix view type in SyntheticCategoryController to :list

app/views/collections/_media_display.html.erb
=> Don't try to use custom collection media in admin, where apparently we don't have it yet.

app/assets/stylesheets/local/homepage.scss
=> Correct searchbox element heights in ff / safari

app/views/catalog/_search_form.html.erb
=> Hide search dropdown for non-staff users

app/assets/stylesheets/local/site-wide.scss, app/views/_logo.html.erb
=> Add 'beta' to header

app/views/_masthead.html.erb, config/environments/production.rb, config/initializers/sufia.rb, config/routes.rb
=> change contact to mailto and 404 the form page

config/deploy.rb, config/deploy/staging.rb
=> Update staging config to account for broken-out solr machine

lib/tasks/chf_tasks.rake
Does not fix, but gives us another tool in dealing with situations like in #619
=> rerun_failed_fixity_checks rake task

app/services/characterization_service_override.rb, lib/minimagick/tool.rb, lib/minimagick_patch.rb, lib/tasks/chf_tasks.rake, spec/fixtures/size_conflict.tiff.fits.xml, spec/services/characterization_service_spec.rb, spec/support/file_set_helper.rb
refs #624; before the issue can be closed we need to run the new task
=> Fix characterization

app/helpers/riiif_helper.rb, app/models/solr_document.rb, app/presenters/chf/file_set_presenter.rb, app/presenters/curation_concerns/generic_work_show_presenter.rb, app/views/curation_concerns/base/_chf_image_viewer.html.erb, spec/factories/file_set.rb, spec/presenters/chf/file_set_presenter_spec.rb, spec/presenters/curation_concerns/generic_work_show_presenter_spec.rb
so viewer doesn't need to hit fedora.
=> Use indexed original_file id from presenters

app/assets/javascripts/chf_image_viewer.js
Need to make sure the modal stays focused, if we're hiding a UI element that was browser focused.
=> Viewer, fix focus on hidden UI

app/assets/javascripts/chf_image_viewer.js, app/assets/stylesheets/local/show.scss, app/helpers/riiif_helper.rb, app/views/curation_concerns/base/_chf_download_menu.html.erb, app/views/curation_concerns/base/_chf_image_viewer.html.erb, app/views/curation_concerns/base/_chf_image_viewer_navbar.html.erb, app/views/curation_concerns/base/_show_page_image.html.erb, app/views/curation_concerns/base/_show_page_image_download_menu.html.erb
* full size JPG powered by riiif
* riiif_image_url helper
* live download links in viewer
Closes #635
=> Downloads improvements

app/presenters/curation_concerns/generic_work_show_presenter.rb, app/views/curation_concerns/base/_chf_image_viewer.html.erb, spec/presenters/curation_concerns/generic_work_show_presenter_spec.rb
=> non-viewable members hidden on work show page and in viewer

app/services/iiif_authorization_service.rb, config/initializers/riiif.rb, spec/services/iiif_authorization_service_spec.rb
as per https://github.com/RepoCamp/ahc/wiki/IIIF#adding-authorization
=> Authorize for riiif image access, refs #617

app/models/chf/env.rb, lib/chf/utils/riiif_original_preloader.rb, lib/tasks/chf_tasks.rake
eg, on app server:
RAILS_ENV=production INTERNAL_RIIIF_URL=http://172.31.63.136 bundle exec rake chf:riiif:preload_originals
Refs #675
=> Rake task to get riiif to preload originals

app/assets/stylesheets/local/show.scss
without messing things up with too short a max-height in some screen sizes
Closes #676
=> one more attempt at sanity max-height on images

app/helpers/riiif_helper.rb
@hackmastera  spotted the bug from code alone at:
https://github.com/chemheritage/chf-sufia/pull/687#discussion_r127051821
go you.
=> fix click on child work to launch viewer

app/indexers/chf/file_set_indexer.rb, app/models/file_set.rb
Copy of what is in riiif branch. Will have to resolve on merging master/riiif.
We want this here so master can be indexing what riiif will need, before
we deploy riiif
=> Add original_file_id indexing to master.

public/robots.txt
I was going to make it lower but considering we have some objects with poor load times I changed my mind.
=> Add crawl-delay of 5 seconds, fixes #692

lib/tasks/dev.rake, spec/factories/generic_works.rb
To let me create one with 200 filesets.
This code is kind of spaghetti now, refactor at some point, maybe not actually
using factories. But good for now
=> more flexibility in task/factory to create a dev work

lib/tasks/dev.rake
eg
NUM_PUBLIC_WORKS=1 NUM_PRIVATE_WORKS=0 NUM_CHILD_WORKS=196 NUM_FILESETS=498 TITLE_BASE=Ramelli-Like bundle exec rake dev:data[jrochkind@chemheritage.org]
=> WIP enhanced dev:data task taht can create child works

lib/tasks/chf_tasks.rake
use `rake -D` to see full descriptions; it takes a pattern so you can
do, e.g. `bundle exec rake -D chf`
=> Add example invocations to many rake tasks

app/helpers/image_service_helper.rb, app/helpers/member_helper.rb, app/services/chf/iiif_url_service.rb, app/views/curation_concerns/base/_chf_image_viewer.html.erb, spec/helpers/image_service_helper_spec.rb
Meant to support polymorphism when we allow various types of image service sources
Won't commit without review, but going to use this as a base for dzi branch
=> Extract IiifUrlService to a helper object

app/assets/javascripts/chf_image_viewer.js, app/assets/stylesheets/local/chf_image_viewer.scss, app/views/curation_concerns/base/_chf_image_viewer.html.erb
Fallback is the /downloads/$id?file=jpeg link as source. 
Tile-source-agnostic, just a viewer function.
=> viewer has fallback url, with alert warning

app/views/curation_concerns/base/_show_page_image.html.erb, app/views/curation_concerns/base/show.html.erb
@jrochkind I think this got overlooked in some refactoring. Please take a close look and make sure this matches your understanding of the current state of the codebase!
=> Fix show page for work with more than one member

config/application.rb
Useful for debugging sometimes
=> allow setting of Rails log_level from ENV

app/assets/javascripts/chf_image_viewer.js, app/helpers/image_service_helper.rb, app/views/curation_concerns/base/_show_page_image.html.erb
=> viewer, various keyboard control fixes

app/presenters/curation_concerns/generic_work_show_presenter.rb
=> fix aspectratio for child works

app/views/sufia/homepage/index.html.erb
=> New home page text

app/assets/stylesheets/local/results.scss
PR into visual_ux_refresh branch
=> Clean up and better branding of facets sidebar.

app/assets/stylesheets/local/homepage.scss, app/views/sufia/homepage/index.html.erb
with more space made for it in the pretty hacky CSS
Closes #759
=> longer homepage intro text

app/controllers/catalog_controller.rb, app/models/concerns/generic_metadata.rb
Needs a reindex, then recommit without show: false on facet
Ref #811 close after reindex
=> Exhibition facet

app/controllers/catalog_controller.rb, app/indexers/chf/generic_work_indexer.rb
Facet values are a bit weird, open==public, restricted==private, authenticated==chf-only
Requires re-index to work, but okay to deploy without, facet will just be missing/incomplete until finished.
=> visibilty facet for staff-only

app/indexers/chf/generic_work_indexer.rb, app/indexers/chf/generic_work_indexer/date_values.rb, solr/config/schema.xml
Separate PR so it can be in master first for a reindex.
Towards #712
=> Index earliest and latest date_of_works for sorting

app/controllers/catalog_controller.rb, app/helpers/application_helper.rb
=> user-facing labels for 'visbility' facet that make more sense

app/controllers/catalog_controller.rb
=> fix order of fields on results page

config/application.rb
=> new exhibition values

config/initializers/blacklight.rb
=> Tell blacklight to use POST rather than GET with Solr

config/application.rb
=> add genre value 'Medical equipment & supplies'

app/assets/stylesheets/local/homepage.scss, app/views/sufia/homepage/index.html.erb
With changes and crazy arithmatic to try to keep whitespace and alignment looking good at all
screen sizes.
Ref #761
=> Smaller front-page hero

app/assets/stylesheets/local/site-wide.scss, app/helpers/image_service_helper.rb, app/presenters/curation_concerns/generic_work_show_presenter.rb, app/views/application/robots.txt.erb, app/views/curation_concerns/base/_chf_meta_tags.html.erb, app/views/curation_concerns/base/_social_media.html.erb, app/views/curation_concerns/base/show.html.erb, app/views/shared/_footer.html.erb, config/application.rb
=> improve social media sharing buttons

app/assets/stylesheets/local/results.scss, app/controllers/catalog_controller.rb, app/controllers/collections_controller.rb, app/controllers/concerns/parent_lookup.rb, app/views/curation_concerns/generic_works/_generic_work.html.erb
=> "Part of" on search results

config/application.rb
=> add file_creator Conservation Center for Art & Historic Artifacts

app/presenters/curation_concerns/member_presenter_factory_override.rb
=> misunderstood attempt to reuse access control logic, should have been OR not AND

app/controllers/catalog_controller.rb
=> remove results-view-type choices

app/controllers/catalog_controller.rb
=> move date facet to top of facet list

app/controllers/sufia/homepage_controller_override.rb, app/views/sufia/homepage/index.html.erb
=> real count of public works on home page

solr/config/solrconfig.xml
=> solr mm is 100% always

app/models/concerns/generic_metadata.rb, app/views/curation_concerns/base/show.html.erb, app/views/static/faq.html.erb, lib/tasks/chf_tasks.rake, spec/factories/generic_works.rb, spec/models/generic_work_spec.rb, spec/views/curation_concerns/base/show.html.erb_spec.rb
Waiting on task success on staging.
=> rebrand courtesy of lines

app/controllers/sufia/homepage_controller_override.rb, app/models/search_builder/home_page.rb
=> home page search builder is only public things, but of all types

app/controllers/application_controller.rb, spec/features/search_feature_spec.rb
Raised an error when limiting to 'my works' redirected to my/works controller.
https://app.honeybadger.io/projects/53196/faults/36500802
Fixes #972
=> only try to use new fancy editable query constraint on user-facing catalog

lib/tasks/chf_tasks.rake
* catch and change
* catch and change bare http://chemheritage.org
=> improve rebrand data migration urls

app/views/static/about.html.erb
Just a quick fix on a url typo in the About page. @jrochkind I don't think this needs a review.
=> removed extra w in url

config/application.rb
=> New genre term: Pesticides

Gemfile.lock
https://groups.google.com/d/msgid/samvera-tech/d5bb3f30-ce13-3299-9ef6-153ca82531f8%40gmail.com.
=> update hydra-works to 0.17.0

app/assets/javascripts/popovers.js, app/assets/stylesheets/local/site-wide.scss, app/assets/stylesheets/local/work-show.scss, app/controllers/curation_concerns/generic_works_controller.rb, app/helpers/application_helper.rb, app/helpers/image_service_helper.rb, app/models/chf/ris_serializer.rb, app/models/chf/ris_serializer_base.rb, app/services/chf/create_derivatives_on_s3_service.rb, app/views/application/_query_constraint_as_form.html.erb, app/views/curation_concerns/base/show.html.erb, config/initializers/mime_types.rb, config/routes.rb, spec/features/search_feature_spec.rb, spec/models/chf/ris_serializer_spec.rb
Closes #565
We probably want to create new tickets fori (@mdimeo):
* Looking into improving Zotero extension "toolbar" button
* Looking into improving "child work" issue (including current cases where there is no parent in the system for the 'child')
=> RIS export

app/controllers/collections_show_controller.rb, app/models/ability.rb, app/models/search_builder.rb, app/views/collections_show/index.html.erb
And both for staff users. 
Closes #887 and ref #848
=> collection count on collection show lists _public_ item count

config/routes.rb
=> Don't eat /collection/new with our custom collection show controller

app/assets/stylesheets/local/footer.scss, app/views/shared/_footer.html.erb
=> footer updates per zack

config/application.rb
=> new genre term 'Publications'

app/controllers/catalog_controller.rb, app/forms/batch_edit_form.rb, app/forms/batch_upload_form.rb, app/forms/curation_concerns/generic_work_form.rb, app/models/concerns/generic_metadata.rb, app/models/solr_document.rb, app/presenters/chf/index_presenter.rb, app/presenters/curation_concerns/generic_work_show_presenter.rb, app/views/curation_concerns/base/show.html.erb, app/views/curation_concerns/generic_works/_generic_work.html.erb, config/locales/generic_work.en.yml, spec/forms/batch_edit_form_spec.rb, spec/forms/batch_upload_form_spec.rb, spec/forms/curation_concerns/generic_work_form_spec.rb
=> new metadata field: source

config/locales/generic_work.en.yml
=> update physical container edit hint

lib/chf/solr_batch_adder.rb, lib/tasks/chf_tasks.rake
Will close #963 
Does not currently handle fixing group membership for changed accounts. Not sure if we need to, if we use that at all?
Not 100% confident that there aren't any other things hiding in sufia data stores that might have to be changed.
=> rake task to change email addresses of staff account to @sciencehistory.org

app/models/generic_work.rb, app/models/inscription.rb, spec/features/new_work_feature_spec.rb
Here's a naive attempt to fix https://github.com/sciencehistory/chf-sufia/issues/428. Mostly submitting this as an exercise; I don't claim to know exactly what I'm doing.
=> Update label before index

app/views/curation_concerns/base/_social_media.html.erb
=> tumblr share as photo type

app/presenters/curation_concerns/generic_work_show_presenter.rb
=> Account for records with nil identifiers

app/assets/stylesheets/local/site-wide.scss, app/assets/stylesheets/local/work-show.scss, app/presenters/curation_concerns/generic_work_show_presenter.rb, app/renderers/chf_related_url_attribute_renderer.rb, app/views/curation_concerns/base/_chf_related_work.html.erb, app/views/curation_concerns/base/show.html.erb
Just by filtering out from the existing related_urls field
Closes #338
=> Related works

spec/features/batch_edit_feature_spec.rb
Here you go.
This test was passing locally for me, but it's now failing locally. Will get to the bottom of this.
=> Temporarily disabling one of the feature tests pending investigation

app/assets/javascripts/accept_cookies_banner.js, app/assets/stylesheets/local/__variables.scss, app/assets/stylesheets/local/footer.scss, app/views/layouts/chf.html.erb, app/views/layouts/homepage.html.erb, app/views/shared/_accept_cookies_banner.html.erb, app/views/sufia/homepage/index.html.erb, spec/features/collection_feature_spec.rb
Rough draft of the "Accept Cookies" banner.
=> GDPR "accept cookies" banner

config/routes.rb
In rails routes, first routes take precedence, so we 'override' by adding a path first.
backport of https://github.com/samvera/browse-everything/commit/6416ce9d611a3f24d9684916edc0484e737c34d9
=> patch BrowseEverything route to handle periods in directory names

Gemfile.lock
https://groups.google.com/forum/#!topic/ruby-security-ann/2S9Pwz2i16k
=> update sprockets to 3.7.2

app/models/user.rb, db/migrate/20180620153226_add_locked_out_to_users.rb, db/schema.rb, lib/tasks/chf_tasks.rake
Fixes https://github.com/sciencehistory/chf-sufia/issues/1107 . We won't add tests for this one (see below.)
=> Locking out users

app/assets/stylesheets/local/homepage.scss, app/controllers/sufia/homepage_controller_override.rb, app/helpers/recent_items_helper.rb, app/views/sufia/homepage/_featured_collection.html.erb, app/views/sufia/homepage/_recent_items.html.erb, app/views/sufia/homepage/index.html.erb
Here's a very simple proof of concept that we can use to have a more grounded discussion about what we want. I decided not to spend too much time worrying about the design before we have more specifics, so it still looks sloppy.
For now, I'm taking 15 recent works, dumping them into a bag, shuffling the bag, and taking 6 out of them to show on the front page. I reshuffle the bag every minute and pick 6 new items-- but out of the same bag of 15 recent works. All three of these parameters are easy to change, but I had to start somewhere.
I'm calling the new section "Featured items". The section below it (which formerly didn't have a title, now also gets a title: "Collections".
Fixes #538 .
=> Recent Items

config/application.rb
Fixes #1118.
This looks pretty simple; let me know if I'm missing anything.
=> Add "age of alchemy" exhibition

app/controllers/catalog_controller.rb
Fixes #1125 . We're already subclassing catalog#index , so I'm just swapping the parameters before we call super.
=> If the user enters an impossible date range, swap the dates.

Gemfile.lock
To be able to succesfully download solr from apache or apache mirrors. 
https://groups.google.com/forum/#!topic/samvera-tech/sOnSa2NEZQg
=> update solr_wrapper to 2.0

app/assets/javascripts/chf_image_viewer.js, app/controllers/downloads_controller_override.rb, app/helpers/image_service_helper.rb, app/helpers/member_helper.rb, app/indexers/chf/file_set_indexer.rb, app/indexers/chf/generic_work_indexer.rb, app/jobs/create_dzi_job.rb, app/presenters/chf/file_set_presenter.rb, app/presenters/curation_concerns/generic_work_show_presenter.rb, app/services/chf/create_derivatives_on_s3_service.rb, app/views/curation_concerns/base/show.html.erb, config/sitemap.rb, lib/chf/env.rb, lib/chf/util.rb
=> wip PDF originals

Gemfile.lock
=> updating rubyzip 1.2.1 -> 1.2.2

config/application.rb
=> Adding 'Center for Oral History' option to the file_creator dropdown

config/application.rb
=> Adding money as a genre

Gemfile.lock
For possible vulnerabilities
https://rubysec.com/advisories/rack-CVE-2018-16470
https://rubysec.com/advisories/rack-CVE-2018-16471
=> update rack version

app/presenters/chf/collection_show_presenter.rb, app/presenters/curation_concerns/generic_work_show_presenter.rb, app/views/catalog/_search_sidebar.html.erb
Fixes https://github.com/sciencehistory/chf-sufia/issues/1178 .
=> Using https for OPAC (Sierra) links

config/application.rb
- Adding a 'Figurines' genre fixes #1210 
- Adding an 'Object Explorer' exhibition fixes #1212 
- Sorting the 'Exhibitions' field alphabetically and using double-quotes for all strings.
=> Simple changes to config/application.rb

app/helpers/citation_rendering_helper.rb, app/models/chf/citable_attributes.rb, app/models/chf/citable_attributes/renderer.rb, spec/factories/generic_works.rb, spec/models/chf/citable_attributes_spec.rb
=> Fix oral histories citations

app/exporters/collection_exporter.rb, app/exporters/exporter.rb, app/exporters/file_set_exporter.rb, app/exporters/generic_work_exporter.rb, lib/tasks/export.rake
On the chf-sufia server, run `bundle exec rake chf:export`.
Note:
`ONLY_COLLECTIONS='j6731386g' RAILS_ENV=production bundle exec rake chf:export` will export only that one collection (useful for testing.)
The export will create a batch of json files in `tmp/export`.
Move those files into scihist_digicoll's directory, at: `/tmp/import`.
Then, run `bundle exec rake scihist_digicoll:import`.
=> Export to scihist-digicoll

config/application.rb
Just adding one genre. Required for today's metadata "dash", so  I plan to merge & push this afternoon.
=> Trivial change - adding genre

config/deploy/staging.rb
For the Ubuntu 18.04 LTS upgrade.
=> The new solr IP address for staging.

app/exporters/exporter.rb, app/exporters/generic_work_exporter.rb, lib/tasks/export.rake
=> Export to scihist digicoll

app/helpers/image_service_helper.rb, config/initializers/mime_types.rb
- Adding audio/x-flac to recognized mime-types
- Using proper Rails path instead of hard-coded URL
=> A couple adjustments to audio functionality

app/models/chf/citable_attributes.rb, spec/models/chf/citable_attributes_spec.rb
As reported by honeybadger:
https://app.honeybadger.io/projects/53196/faults/49222550#notice-trace
=> fix for bug triggered by nil date in oral history citation code

config/application.rb
Just changing the order of one line in a file.
=> fixing order of school_of in the dropdown

app/views/application/robots.txt.erb
Closes #1271
This may take a few days from being pushed out until we see any notable changes.
=> Added list of SEO or Ad bots to block to robots file

app/forms/curation_concerns/generic_work_form.rb, app/views/curation_concerns/base/_attribute_rows.html.erb, app/views/curation_concerns/base/show.html.erb
=> fixing placement of digitization_funder in form and item show page
